"""Fraud detection prediction logic."""

import joblib
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Dict, Any, List, Tuple
import logging
import sys
sys.path.append(str(Path(__file__).parent.parent))

from src.features.feature_engineer import FeatureEngineer

logger = logging.getLogger(__name__)


CAVEAT_MESSAGE = (
    "All predictions are based on pseudo-labels generated by an unsupervised ensemble "
    "(Isolation Forest + LOF + OCSVM). The model replicates that ensemble's decisions — "
    "it is NOT validated against verified fraud ground truth. Human review of flagged "
    "listings is required before any real-world action."
)


# Human-readable risk factor descriptions
RISK_FACTOR_LABELS = {
    'price_iqr_deviation': "Price is {value:.1f}× outside the typical range for this area",
    'price_above_200pct_expected': "Price is more than double the expected value for this location",
    'price_below_50pct_expected': "Price is less than half the expected value for this location",
    'geo_anomaly': "Location coordinates fall outside Karachi city boundaries",
    'ghost_listing_flag': "Property matches characteristics of ghost listings (frequent reposting of identical details)",
    'bath_bed_extreme': "Unusual bathroom-to-bedroom ratio detected",
    'price_loc_zscore': "Price is {value:.1f} standard deviations above the area average",
    'weekly_volume_ratio': "This area shows {value:.1f}× higher listing activity than typical",
    'relisting_intensity': "Property has been relisted multiple times (intensity: {value:.1f})",
    'high_cv_location': "This area has highly inconsistent pricing patterns"
}

# CORRECTED: the previous value here (0.01, 0.20) was not actually what NB06
# produces. NB06 Section 9 (CV F1-threshold-optimization) prints a threshold
# of ~0.5822 on every run, with individual fold thresholds ranging
# 0.507-0.680 — nowhere near [0.01, 0.20]. That wrong range caused a real bug
# (see _map_risk_level docstring below): the old multiplier-based tiers
# (3*t, 6*t) assumed a small threshold and broke once t landed at ~0.58.
#
# _map_risk_level and _get_confidence_tier have since been rewritten to be
# threshold-magnitude-independent (they work correctly for any t in (0, 1)),
# so this range is now purely informational / a sanity check that a newly
# regenerated threshold artifact still looks like a real CV-optimized value
# rather than, say, an accidental 0.0 or 1.0 from a broken save.
EXPECTED_THRESHOLD_RANGE = (0.45, 0.75)


class FraudDetector:
    """
    Fraud detection inference engine.

    Loads the trained model and all artifacts, performs feature engineering,
    and generates predictions with risk levels and top risk factors.
    """

    def __init__(
        self,
        model_path: str = "models/fraud_detector_v1.pkl",
        artifacts_path: str = "models/artifacts"
    ):
        """
        Load model and preprocessing artifacts.

        Args:
            model_path: Path to trained model pickle file
            artifacts_path: Path to artifacts directory
        """
        self.model_path = Path(model_path)
        self.artifacts_path = Path(artifacts_path)

        # Load model
        self.model = joblib.load(self.model_path)

        # Load threshold
        threshold_info = joblib.load(self.artifacts_path / "fraud_detector_v1_threshold.pkl")
        self.threshold = threshold_info['threshold']

        # Load metadata
        self.metadata = joblib.load(self.artifacts_path / "fraud_detector_v1_metadata.pkl")

        # Load scaler
        self.scaler = joblib.load(self.artifacts_path / "scaler_robust_v1.pkl")

        # Load feature list
        self.feature_cols = joblib.load(self.artifacts_path / "model_feature_cols.pkl")

        # Initialize feature engineer
        self.feature_engineer = FeatureEngineer(artifacts_path=str(self.artifacts_path))

        # FIX: model_card (metadata) uses keys like 'model_type', 'best_params',
        # 'cv_pr_auc_mean', etc. (set in NB06 Section 10) — not 'hyperparameters'
        # / 'metrics' / 'training_date', which don't exist in the saved metadata
        # and were silently returning empty dicts / None via .get() defaults.
        # Storing model_type here also lets predict_single/predict_batch report
        # which algorithm actually produced the score (previously hardcoded to
        # imply Random Forest everywhere, even after NB06 selected XGBoost).
        self.model_type = self.metadata.get('model_type', 'unknown')

        print(f"[OK] Model loaded: {self.model_path.name}")
        print(f"[OK] Model type: {self.model_type}")
        print(f"[OK] Threshold: {self.threshold:.4f}")
        print(f"[OK] Features: {len(self.feature_cols)}")

        # Sanity check only — no longer load-bearing for risk-level correctness.
        # _map_risk_level and _get_confidence_tier are now threshold-magnitude-
        # independent, so an out-of-range threshold no longer breaks tiering;
        # this just flags that something may have gone wrong upstream in NB06.
        lo, hi = EXPECTED_THRESHOLD_RANGE
        if not (lo <= self.threshold <= hi):
            logger.warning(
                f"Loaded threshold ({self.threshold:.4f}) is outside the "
                f"range [{lo}, {hi}] normally produced by NB06's CV "
                f"F1-optimization (Section 9). Risk-level tiering will still "
                f"work correctly at any threshold value, but this is worth "
                f"checking — it may mean fraud_detector_v1_threshold.pkl is "
                f"stale or was saved from an interrupted NB06 run."
            )

    def predict_single(self, listing: Dict[str, Any]) -> Dict[str, Any]:
        """
        Predict anomaly for a single listing.

        Args:
            listing: Dict with raw listing data

        Returns:
            Dict with prediction results
        """
        # Feature engineering
        features_df = self.feature_engineer.transform(listing)

        # Scale features
        features_scaled = self.scaler.transform(features_df)

        # Predict probability
        prob = self.model.predict_proba(features_scaled)[0, 1]

        # Apply threshold
        is_anomaly = bool(prob >= self.threshold)

        # Map to risk level
        risk_level, risk_label = self._map_risk_level(prob)

        # Extract top risk factors
        top_risk_factors = self._extract_risk_factors(features_df.iloc[0], prob)

        # Confidence tier
        confidence_tier = self._get_confidence_tier(prob)

        return {
            "anomaly_probability": float(prob),
            "is_anomaly": is_anomaly,
            "risk_level": risk_level,
            "risk_label": risk_label,
            "confidence_tier": self._format_confidence_tier(confidence_tier),
            "top_risk_factors": top_risk_factors,
            "model": f"fraud_detector_v1 ({self.model_type})",
            "threshold": self.threshold,
            "caveat": CAVEAT_MESSAGE
        }

    def predict_batch(self, listings: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Predict anomalies for multiple listings.

        Args:
            listings: List of dicts with raw listing data

        Returns:
            Dict with batch prediction results
        """
        # Convert to DataFrame
        df = pd.DataFrame(listings)

        # Feature engineering
        features_df = self.feature_engineer.transform(df)

        # Scale features
        features_scaled = self.scaler.transform(features_df)

        # Predict probabilities
        probs = self.model.predict_proba(features_scaled)[:, 1]

        # Apply threshold
        is_anomalies = probs >= self.threshold

        # Build results
        predictions = []
        for i, (prob, is_anom) in enumerate(zip(probs, is_anomalies)):
            risk_level, risk_label = self._map_risk_level(prob)
            predictions.append({
                "index": i,
                "anomaly_probability": float(prob),
                "is_anomaly": bool(is_anom),
                "risk_level": risk_level,
                "risk_label": risk_label
            })

        anomalies_detected = int(is_anomalies.sum())

        return {
            "total": len(listings),
            "anomalies_detected": anomalies_detected,
            "anomaly_rate": float(anomalies_detected / len(listings)),
            "predictions": predictions
        }

    def _map_risk_level(self, prob: float) -> Tuple[str, str]:
        """
        Map probability to risk level and label, scaled relative to this
        model's decision threshold rather than fixed absolute cutoffs.

        FIXED (previous bug): the old version used pure multiples of the
        threshold (6*t, 3*t), capped at absolute ceilings (0.70, 0.40) as a
        guard-rail. That guard-rail was itself tuned assuming a small
        threshold (the old code believed t sat in [0.01, 0.20]). The real
        threshold NB06 produces is ~0.5822 — and at that value the HIGH
        ceiling (0.40) sits *below* the MEDIUM floor (t = 0.5822). Since the
        branches are checked top-down, any prob in [0.40, 0.5822) matched
        the HIGH branch before ever reaching the MEDIUM check, making MEDIUM
        unreachable — and worse, listings with prob < threshold (i.e.
        is_anomaly=False) could still be labelled "HIGH / Suspicious
        Listing", which is a visible contradiction.

        This version instead defines each tier as a fraction of the
        remaining headroom between the threshold and 1.0, so the ordering
        CRITICAL > HIGH > MEDIUM = threshold holds by construction for any
        threshold in (0, 1) — no capping hacks needed, and it stays correct
        if the model is retrained and the threshold shifts again.

        Args:
            prob: Anomaly probability

        Returns:
            Tuple of (risk_level, risk_label)
        """
        t = self.threshold
        headroom = max(1.0 - t, 1e-6)  # room between threshold and the max possible prob

        if prob >= t + 0.60 * headroom:
            return "CRITICAL", "High-Alert Anomaly"
        elif prob >= t + 0.25 * headroom:
            return "HIGH", "Suspicious Listing"
        elif prob >= t:
            return "MEDIUM", "Possible Anomaly"
        else:
            return "LOW", "Normal Listing"

    def _get_confidence_tier(self, prob: float) -> str:
        """
        Get confidence tier based on distance from threshold, normalized by
        the distance to the nearest boundary (0 or 1) on that side.

        FIXED (previous bug): the old version used
        |prob - t| / t, which only worked by coincidence at t ~ 0.58 — for
        other threshold values (e.g. a future retrain landing at t > 0.4)
        it would have silently made HIGH_CONFIDENCE unreachable, the same
        class of bug as in _map_risk_level. This version instead expresses
        distance as a fraction of the maximum possible distance on whichever
        side of the threshold prob falls, so the result is always in [0, 1]
        and both tiers stay reachable for any threshold.
        """
        t = self.threshold
        if prob >= t:
            span = max(1.0 - t, 1e-6)
            normalized_distance = (prob - t) / span
        else:
            span = max(t, 1e-6)
            normalized_distance = (t - prob) / span

        if normalized_distance >= 0.60:
            return "HIGH_CONFIDENCE"
        elif normalized_distance >= 0.25:
            return "MEDIUM_CONFIDENCE"
        else:
            return "LOW_CONFIDENCE"

    def _format_confidence_tier(self, tier: str) -> str:
        """
        Format confidence tier for display.

        Args:
            tier: Raw confidence tier (e.g., 'HIGH_CONFIDENCE')

        Returns:
            Formatted string (e.g., 'High')
        """
        tier_map = {
            'HIGH_CONFIDENCE': 'High',
            'MEDIUM_CONFIDENCE': 'Medium',
            'LOW_CONFIDENCE': 'Low (close to threshold)'
        }
        return tier_map.get(tier, tier)

    def _extract_risk_factors(self, features: pd.Series, prob: float) -> List[str]:
        """
        Extract top risk factors contributing to high anomaly score.

        Args:
            features: Feature vector for the listing
            prob: Predicted probability

        Returns:
            List of human-readable risk factor descriptions
        """
        risk_factors = []

        # FIXED: Convert to dict for safe .get() usage (pd.Series.get() doesn't handle NaN properly)
        f = features.to_dict()

        # Check key anomaly indicators with human-readable descriptions
        if f.get('price_iqr_deviation', 0) > 5:
            risk_factors.append(
                RISK_FACTOR_LABELS['price_iqr_deviation'].format(
                    value=f['price_iqr_deviation']
                )
            )

        if f.get('price_above_200pct_expected', 0) == 1:
            risk_factors.append(RISK_FACTOR_LABELS['price_above_200pct_expected'])

        if f.get('price_below_50pct_expected', 0) == 1:
            risk_factors.append(RISK_FACTOR_LABELS['price_below_50pct_expected'])

        if f.get('geo_anomaly', 0) == 1:
            risk_factors.append(RISK_FACTOR_LABELS['geo_anomaly'])

        if f.get('ghost_listing_flag', 0) == 1:
            risk_factors.append(RISK_FACTOR_LABELS['ghost_listing_flag'])

        if f.get('bath_bed_extreme', 0) == 1:
            risk_factors.append(RISK_FACTOR_LABELS['bath_bed_extreme'])

        if f.get('price_loc_zscore', 0) > 3:
            risk_factors.append(
                RISK_FACTOR_LABELS['price_loc_zscore'].format(
                    value=f['price_loc_zscore']
                )
            )

        if f.get('weekly_volume_ratio', 0) > 3:
            risk_factors.append(
                RISK_FACTOR_LABELS['weekly_volume_ratio'].format(
                    value=f['weekly_volume_ratio']
                )
            )

        if f.get('relisting_intensity', 0) > 3:
            risk_factors.append(
                RISK_FACTOR_LABELS['relisting_intensity'].format(
                    value=f['relisting_intensity']
                )
            )

        if f.get('high_cv_location', 0) == 1:
            risk_factors.append(RISK_FACTOR_LABELS['high_cv_location'])

        # If no specific factors triggered, use generic message
        if not risk_factors:
            if prob >= 0.5:
                risk_factors.append("Multiple subtle anomaly signals detected across features")
            else:
                risk_factors.append("No major anomaly indicators detected")

        # Return top 5 factors
        return risk_factors[:5]

    def get_model_info(self) -> Dict[str, Any]:
        """
        Get model metadata information.

        FIXED (previous bug): this previously read 'training_date',
        'hyperparameters', and 'metrics' from self.metadata — keys that do
        not exist in the model_card NB06 Section 10 actually saves (it uses
        'model_type', 'best_params', 'cv_pr_auc_mean', etc. instead). The
        old code didn't crash, because .get() fell back to None / {} for
        every one of them, so the endpoint silently returned an
        uninformative response instead of the rich comparison/tuning info
        that was actually captured during training. This version reads the
        real keys.
        """
        return {
            "model_name": "fraud_detector_v1",
            "version": "1.0.0",
            "threshold": self.threshold,
            "feature_count": len(self.feature_cols),
            "model_type": self.model_type,
            "tuning_strategy": self.metadata.get('tuning_strategy'),
            "selected_by": self.metadata.get('selected_by'),
            "best_params": self.metadata.get('best_params', {}),
            "cv_pr_auc_mean": self.metadata.get('cv_pr_auc_mean'),
            "cv_pr_auc_std": self.metadata.get('cv_pr_auc_std'),
            "test_pr_auc_vs_heuristic": self.metadata.get('test_pr_auc_vs_heuristic'),
            "test_roc_auc_vs_heuristic": self.metadata.get('test_roc_auc_vs_heuristic'),
            "label_caveat": self.metadata.get('label_caveat'),
            "caveat": CAVEAT_MESSAGE
        }
